### ISSUE TITLE
Circuit sometimes crashes when rapidly switching operations

### ISSUE THREAD

**Issue by Trolldemorted** [ENOFLAG/ChallengePad#9]
```
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  | System.InvalidOperationException: Sequence contains no matching element
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |    at System.Linq.ThrowHelper.ThrowNoMatchException()
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |    at ChallengePad.Pages.Index.HandleOperationSelection(Int64 id) in /src/Pages/Index.razor:line 250
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |    at ChallengePad.Pages.Index.HandleOperationSelection(ChangeEventArgs args) in /src/Pages/Index.razor:line 240
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |    at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  | fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |       Unhandled exception in circuit '86zDPJq-HdO8ZiYsjFrZrdv5nFxCoSrn4vHKp-oGyrA'.
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  | System.InvalidOperationException: Sequence contains no matching element
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |    at System.Linq.ThrowHelper.ThrowNoMatchException()
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |    at ChallengePad.Pages.Index.HandleOperationSelection(Int64 id) in /src/Pages/Index.razor:line 250
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |    at ChallengePad.Pages.Index.HandleOperationSelection(ChangeEventArgs args) in /src/Pages/Index.razor:line 240
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |    at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  | info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |       Executed endpoint '/_blazor'
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  | info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
Apr 17 20:16:04 bastet docker-compose[1749]: challengepad_1  |       Request finished in 50845.8679ms 101
```

**Comment by Trolldemorted** [comment]
fixed by dfa8b36aa8dd5a47b13800ade58c4905e415ce1c
